# gen_exports.py : reads the export table of the original GameAssembly dll and
# generates the files the proxy needs to forward every export at runtime
#   exports.def    - export names/ordinals -> our stubs
#   stubs.asm      - one jmp per export through g_real_exports[]
#   exports_gen.h  - the names in table order (for GetProcAddress), the md5/size
#                    of the original and the table index of every hooked export
#
# runs as a pre-build step, files are only rewritten when their content changes
# usage: python gen_exports.py [path\to\GameAssembly_orig.dll]
import hashlib
import os
import struct
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DLL = os.path.join(HERE, "..", "GameAssembly_orig.dll")
OUTPUTS = ("exports.def", "stubs.asm", "exports_gen.h")

# exports we implement ourselves in C++ instead of a plain jmp stub
HOOKED = {
    "il2cpp_init": "hk_il2cpp_init",
    "il2cpp_init_utf16": "hk_il2cpp_init_utf16",
}
# exports that should not show up in the import lib (matches the original)
PRIVATE = {"DllCanUnloadNow"}
# our own exports for mods, on top of the original ones
EXTRA = ["GL_GetGameAssembly"]


def read_exports(data):
    pe = struct.unpack_from("<I", data, 0x3C)[0]
    if data[pe:pe + 4] != b"PE\0\0":
        sys.exit("not a PE file")
    nsec = struct.unpack_from("<H", data, pe + 6)[0]
    opt_size = struct.unpack_from("<H", data, pe + 20)[0]
    opt = pe + 24
    if struct.unpack_from("<H", data, opt)[0] != 0x20B:
        sys.exit("not a PE32+ (x64) file")
    exp_rva, exp_size = struct.unpack_from("<II", data, opt + 112)

    sections = []
    for i in range(nsec):
        s = opt + opt_size + i * 40
        vsize, va, rawsize, rawptr = struct.unpack_from("<IIII", data, s + 8)
        chars = struct.unpack_from("<I", data, s + 36)[0]
        sections.append((va, max(vsize, rawsize), rawptr, chars))

    def section_of(rva):
        for sec in sections:
            if sec[0] <= rva < sec[0] + sec[1]:
                return sec
        return None

    def off(rva):
        va, _, rawptr, _ = section_of(rva)
        return rva - va + rawptr

    def cstr(rva):
        o = off(rva)
        return data[o:data.index(b"\0", o)].decode()

    e = off(exp_rva)
    base, nfuncs, nnames, funcs, names, ords = struct.unpack_from("<IIIIII", data, e + 16)

    name_of = {}
    for i in range(nnames):
        name_rva = struct.unpack_from("<I", data, off(names) + i * 4)[0]
        idx = struct.unpack_from("<H", data, off(ords) + i * 2)[0]
        name_of[idx] = cstr(name_rva)

    exports = []
    for idx in range(nfuncs):
        rva = struct.unpack_from("<I", data, off(funcs) + idx * 4)[0]
        if rva == 0:
            continue
        if idx not in name_of:
            sys.exit(f"ordinal-only export @{base + idx} is not supported")
        if exp_rva <= rva < exp_rva + exp_size:
            sys.exit(f"{name_of[idx]} is itself a forwarder, not supported")
        sec = section_of(rva)
        if not sec or not (sec[3] & 0x20000000):  # IMAGE_SCN_MEM_EXECUTE
            sys.exit(f"{name_of[idx]} is a data export, a jmp stub can't forward it")
        exports.append((name_of[idx], base + idx))
    return exports


def write_if_changed(name, text):
    path = os.path.join(HERE, name)
    text = text.replace("\n", "\r\n").encode()
    try:
        if open(path, "rb").read() == text:
            return
    except FileNotFoundError:
        pass
    with open(path, "wb") as f:
        f.write(text)
    print(f"gen_exports: wrote {name}")


def main():
    dll = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DLL)
    if not os.path.isfile(dll):
        # lets the project build on machines without the game dll, as long as
        # the generated files are there
        if all(os.path.isfile(os.path.join(HERE, o)) for o in OUTPUTS):
            print(f"gen_exports: warning: {dll} not found, keeping the existing generated files")
            return
        sys.exit(f"gen_exports: error: {dll} not found and no generated files to fall back on")

    data = open(dll, "rb").read()
    exports = read_exports(data)
    names = [name for name, _ in exports]
    missing = [h for h in HOOKED if h not in names]
    if missing:
        sys.exit(f"gen_exports: error: hooked exports missing from the dll: {', '.join(missing)}")

    header = f"generated by gen_exports.py from {os.path.basename(dll)} - do not edit\n"

    text = f"; {header}LIBRARY GameAssembly\nEXPORTS\n"
    for name, ordinal in exports:
        target = HOOKED.get(name, f"p_{name}")
        # the linker wants PRIVATE COM exports without an ordinal (LNK4222)
        suffix = " PRIVATE" if name in PRIVATE else f" @{ordinal}"
        text += f"    {name}={target}{suffix}\n"
    for name in EXTRA:
        text += f"    {name}\n"
    write_if_changed("exports.def", text)

    text = (f"; {header}"
            "; every stub jumps straight into GameAssembly_orig.dll, so the\n"
            "; registers/stack the caller set up reach the real function untouched\n\n"
            "extern g_real_exports:qword\n\n.code\n\n")
    for i, name in enumerate(names):
        if name in HOOKED:
            continue
        text += f"p_{name} proc\n    jmp qword ptr [g_real_exports + {i * 8}]\np_{name} endp\n\n"
    text += "end\n"
    write_if_changed("stubs.asm", text)

    text = (f"// {header}#pragma once\n\n"
            f"// the original GameAssembly, used to find it when it was renamed/moved\n"
            f"constexpr char kOrigMd5[] = \"{hashlib.md5(data).hexdigest()}\";\n"
            f"constexpr unsigned long long kOrigSize = {len(data)};\n\n"
            "// export names in the same order as the stubs in stubs.asm\n"
            "static const char* const kExportNames[] = {\n")
    text += "".join(f'    "{name}",\n' for name in names)
    text += "};\n\n// g_real_exports index of every export hooked in C++\n"
    text += "".join(f"constexpr size_t kExport_{h} = {names.index(h)};\n" for h in HOOKED)
    write_if_changed("exports_gen.h", text)

    print(f"gen_exports: {len(exports)} exports from {dll}")


if __name__ == "__main__":
    main()
