; generated by gen_exports.py from GameAssembly_orig.dll - do not edit
; every stub jumps straight into GameAssembly_orig.dll, so the
; registers/stack the caller set up reach the real function untouched

extern g_real_exports:qword

.code

p_BrotliDecoderCreateInstance proc
    jmp qword ptr [g_real_exports + 0]
p_BrotliDecoderCreateInstance endp

p_BrotliDecoderDecompress proc
    jmp qword ptr [g_real_exports + 8]
p_BrotliDecoderDecompress endp

p_BrotliDecoderDecompressStream proc
    jmp qword ptr [g_real_exports + 16]
p_BrotliDecoderDecompressStream endp

p_BrotliDecoderDestroyInstance proc
    jmp qword ptr [g_real_exports + 24]
p_BrotliDecoderDestroyInstance endp

p_BrotliDecoderIsFinished proc
    jmp qword ptr [g_real_exports + 32]
p_BrotliDecoderIsFinished endp

p_BrotliEncoderCompress proc
    jmp qword ptr [g_real_exports + 40]
p_BrotliEncoderCompress endp

p_BrotliEncoderCompressStream proc
    jmp qword ptr [g_real_exports + 48]
p_BrotliEncoderCompressStream endp

p_BrotliEncoderCreateInstance proc
    jmp qword ptr [g_real_exports + 56]
p_BrotliEncoderCreateInstance endp

p_BrotliEncoderDestroyInstance proc
    jmp qword ptr [g_real_exports + 64]
p_BrotliEncoderDestroyInstance endp

p_BrotliEncoderHasMoreOutput proc
    jmp qword ptr [g_real_exports + 72]
p_BrotliEncoderHasMoreOutput endp

p_BrotliEncoderSetParameter proc
    jmp qword ptr [g_real_exports + 80]
p_BrotliEncoderSetParameter endp

p_CloseNLSocket proc
    jmp qword ptr [g_real_exports + 88]
p_CloseNLSocket endp

p_CloseZStream proc
    jmp qword ptr [g_real_exports + 96]
p_CloseZStream endp

p_CreateNLSocket proc
    jmp qword ptr [g_real_exports + 104]
p_CreateNLSocket endp

p_CreateZStream proc
    jmp qword ptr [g_real_exports + 112]
p_CreateZStream endp

p_DllCanUnloadNow proc
    jmp qword ptr [g_real_exports + 120]
p_DllCanUnloadNow endp

p_DllGetActivationFactory proc
    jmp qword ptr [g_real_exports + 128]
p_DllGetActivationFactory endp

p_Flush proc
    jmp qword ptr [g_real_exports + 136]
p_Flush endp

p_GlobalizationNative_GetTimeZoneDisplayName proc
    jmp qword ptr [g_real_exports + 144]
p_GlobalizationNative_GetTimeZoneDisplayName endp

p_ReadEvents proc
    jmp qword ptr [g_real_exports + 152]
p_ReadEvents endp

p_ReadZStream proc
    jmp qword ptr [g_real_exports + 160]
p_ReadZStream endp

p_SystemNative_FStat2 proc
    jmp qword ptr [g_real_exports + 168]
p_SystemNative_FStat2 endp

p_SystemNative_UTime proc
    jmp qword ptr [g_real_exports + 176]
p_SystemNative_UTime endp

p_WriteZStream proc
    jmp qword ptr [g_real_exports + 184]
p_WriteZStream endp

p_il2cpp_add_internal_call proc
    jmp qword ptr [g_real_exports + 192]
p_il2cpp_add_internal_call endp

p_il2cpp_alloc proc
    jmp qword ptr [g_real_exports + 200]
p_il2cpp_alloc endp

p_il2cpp_allocation_granularity proc
    jmp qword ptr [g_real_exports + 208]
p_il2cpp_allocation_granularity endp

p_il2cpp_array_class_get proc
    jmp qword ptr [g_real_exports + 216]
p_il2cpp_array_class_get endp

p_il2cpp_array_element_size proc
    jmp qword ptr [g_real_exports + 224]
p_il2cpp_array_element_size endp

p_il2cpp_array_get_byte_length proc
    jmp qword ptr [g_real_exports + 232]
p_il2cpp_array_get_byte_length endp

p_il2cpp_array_length proc
    jmp qword ptr [g_real_exports + 240]
p_il2cpp_array_length endp

p_il2cpp_array_new proc
    jmp qword ptr [g_real_exports + 248]
p_il2cpp_array_new endp

p_il2cpp_array_new_full proc
    jmp qword ptr [g_real_exports + 256]
p_il2cpp_array_new_full endp

p_il2cpp_array_new_specific proc
    jmp qword ptr [g_real_exports + 264]
p_il2cpp_array_new_specific endp

p_il2cpp_array_object_header_size proc
    jmp qword ptr [g_real_exports + 272]
p_il2cpp_array_object_header_size endp

p_il2cpp_assembly_get_image proc
    jmp qword ptr [g_real_exports + 280]
p_il2cpp_assembly_get_image endp

p_il2cpp_bounded_array_class_get proc
    jmp qword ptr [g_real_exports + 288]
p_il2cpp_bounded_array_class_get endp

p_il2cpp_capture_memory_snapshot proc
    jmp qword ptr [g_real_exports + 296]
p_il2cpp_capture_memory_snapshot endp

p_il2cpp_class_array_element_size proc
    jmp qword ptr [g_real_exports + 304]
p_il2cpp_class_array_element_size endp

p_il2cpp_class_enum_basetype proc
    jmp qword ptr [g_real_exports + 312]
p_il2cpp_class_enum_basetype endp

p_il2cpp_class_for_each proc
    jmp qword ptr [g_real_exports + 320]
p_il2cpp_class_for_each endp

p_il2cpp_class_from_il2cpp_type proc
    jmp qword ptr [g_real_exports + 328]
p_il2cpp_class_from_il2cpp_type endp

p_il2cpp_class_from_name proc
    jmp qword ptr [g_real_exports + 336]
p_il2cpp_class_from_name endp

p_il2cpp_class_from_system_type proc
    jmp qword ptr [g_real_exports + 344]
p_il2cpp_class_from_system_type endp

p_il2cpp_class_from_type proc
    jmp qword ptr [g_real_exports + 352]
p_il2cpp_class_from_type endp

p_il2cpp_class_get_assemblyname proc
    jmp qword ptr [g_real_exports + 360]
p_il2cpp_class_get_assemblyname endp

p_il2cpp_class_get_bitmap proc
    jmp qword ptr [g_real_exports + 368]
p_il2cpp_class_get_bitmap endp

p_il2cpp_class_get_bitmap_size proc
    jmp qword ptr [g_real_exports + 376]
p_il2cpp_class_get_bitmap_size endp

p_il2cpp_class_get_data_size proc
    jmp qword ptr [g_real_exports + 384]
p_il2cpp_class_get_data_size endp

p_il2cpp_class_get_declaring_type proc
    jmp qword ptr [g_real_exports + 392]
p_il2cpp_class_get_declaring_type endp

p_il2cpp_class_get_element_class proc
    jmp qword ptr [g_real_exports + 400]
p_il2cpp_class_get_element_class endp

p_il2cpp_class_get_events proc
    jmp qword ptr [g_real_exports + 408]
p_il2cpp_class_get_events endp

p_il2cpp_class_get_field_from_name proc
    jmp qword ptr [g_real_exports + 416]
p_il2cpp_class_get_field_from_name endp

p_il2cpp_class_get_fields proc
    jmp qword ptr [g_real_exports + 424]
p_il2cpp_class_get_fields endp

p_il2cpp_class_get_flags proc
    jmp qword ptr [g_real_exports + 432]
p_il2cpp_class_get_flags endp

p_il2cpp_class_get_image proc
    jmp qword ptr [g_real_exports + 440]
p_il2cpp_class_get_image endp

p_il2cpp_class_get_interfaces proc
    jmp qword ptr [g_real_exports + 448]
p_il2cpp_class_get_interfaces endp

p_il2cpp_class_get_method_from_name proc
    jmp qword ptr [g_real_exports + 456]
p_il2cpp_class_get_method_from_name endp

p_il2cpp_class_get_methods proc
    jmp qword ptr [g_real_exports + 464]
p_il2cpp_class_get_methods endp

p_il2cpp_class_get_name proc
    jmp qword ptr [g_real_exports + 472]
p_il2cpp_class_get_name endp

p_il2cpp_class_get_namespace proc
    jmp qword ptr [g_real_exports + 480]
p_il2cpp_class_get_namespace endp

p_il2cpp_class_get_nested_types proc
    jmp qword ptr [g_real_exports + 488]
p_il2cpp_class_get_nested_types endp

p_il2cpp_class_get_parent proc
    jmp qword ptr [g_real_exports + 496]
p_il2cpp_class_get_parent endp

p_il2cpp_class_get_properties proc
    jmp qword ptr [g_real_exports + 504]
p_il2cpp_class_get_properties endp

p_il2cpp_class_get_property_from_name proc
    jmp qword ptr [g_real_exports + 512]
p_il2cpp_class_get_property_from_name endp

p_il2cpp_class_get_rank proc
    jmp qword ptr [g_real_exports + 520]
p_il2cpp_class_get_rank endp

p_il2cpp_class_get_static_field_data proc
    jmp qword ptr [g_real_exports + 528]
p_il2cpp_class_get_static_field_data endp

p_il2cpp_class_get_type proc
    jmp qword ptr [g_real_exports + 536]
p_il2cpp_class_get_type endp

p_il2cpp_class_get_type_token proc
    jmp qword ptr [g_real_exports + 544]
p_il2cpp_class_get_type_token endp

p_il2cpp_class_get_userdata_offset proc
    jmp qword ptr [g_real_exports + 552]
p_il2cpp_class_get_userdata_offset endp

p_il2cpp_class_has_attribute proc
    jmp qword ptr [g_real_exports + 560]
p_il2cpp_class_has_attribute endp

p_il2cpp_class_has_parent proc
    jmp qword ptr [g_real_exports + 568]
p_il2cpp_class_has_parent endp

p_il2cpp_class_has_references proc
    jmp qword ptr [g_real_exports + 576]
p_il2cpp_class_has_references endp

p_il2cpp_class_instance_size proc
    jmp qword ptr [g_real_exports + 584]
p_il2cpp_class_instance_size endp

p_il2cpp_class_is_abstract proc
    jmp qword ptr [g_real_exports + 592]
p_il2cpp_class_is_abstract endp

p_il2cpp_class_is_assignable_from proc
    jmp qword ptr [g_real_exports + 600]
p_il2cpp_class_is_assignable_from endp

p_il2cpp_class_is_blittable proc
    jmp qword ptr [g_real_exports + 608]
p_il2cpp_class_is_blittable endp

p_il2cpp_class_is_enum proc
    jmp qword ptr [g_real_exports + 616]
p_il2cpp_class_is_enum endp

p_il2cpp_class_is_generic proc
    jmp qword ptr [g_real_exports + 624]
p_il2cpp_class_is_generic endp

p_il2cpp_class_is_inflated proc
    jmp qword ptr [g_real_exports + 632]
p_il2cpp_class_is_inflated endp

p_il2cpp_class_is_inited proc
    jmp qword ptr [g_real_exports + 640]
p_il2cpp_class_is_inited endp

p_il2cpp_class_is_interface proc
    jmp qword ptr [g_real_exports + 648]
p_il2cpp_class_is_interface endp

p_il2cpp_class_is_subclass_of proc
    jmp qword ptr [g_real_exports + 656]
p_il2cpp_class_is_subclass_of endp

p_il2cpp_class_is_valuetype proc
    jmp qword ptr [g_real_exports + 664]
p_il2cpp_class_is_valuetype endp

p_il2cpp_class_num_fields proc
    jmp qword ptr [g_real_exports + 672]
p_il2cpp_class_num_fields endp

p_il2cpp_class_set_userdata proc
    jmp qword ptr [g_real_exports + 680]
p_il2cpp_class_set_userdata endp

p_il2cpp_class_value_size proc
    jmp qword ptr [g_real_exports + 688]
p_il2cpp_class_value_size endp

p_il2cpp_current_thread_get_frame_at proc
    jmp qword ptr [g_real_exports + 696]
p_il2cpp_current_thread_get_frame_at endp

p_il2cpp_current_thread_get_stack_depth proc
    jmp qword ptr [g_real_exports + 704]
p_il2cpp_current_thread_get_stack_depth endp

p_il2cpp_current_thread_get_top_frame proc
    jmp qword ptr [g_real_exports + 712]
p_il2cpp_current_thread_get_top_frame endp

p_il2cpp_current_thread_walk_frame_stack proc
    jmp qword ptr [g_real_exports + 720]
p_il2cpp_current_thread_walk_frame_stack endp

p_il2cpp_custom_attrs_construct proc
    jmp qword ptr [g_real_exports + 728]
p_il2cpp_custom_attrs_construct endp

p_il2cpp_custom_attrs_free proc
    jmp qword ptr [g_real_exports + 736]
p_il2cpp_custom_attrs_free endp

p_il2cpp_custom_attrs_from_class proc
    jmp qword ptr [g_real_exports + 744]
p_il2cpp_custom_attrs_from_class endp

p_il2cpp_custom_attrs_from_field proc
    jmp qword ptr [g_real_exports + 752]
p_il2cpp_custom_attrs_from_field endp

p_il2cpp_custom_attrs_from_method proc
    jmp qword ptr [g_real_exports + 760]
p_il2cpp_custom_attrs_from_method endp

p_il2cpp_custom_attrs_get_attr proc
    jmp qword ptr [g_real_exports + 768]
p_il2cpp_custom_attrs_get_attr endp

p_il2cpp_custom_attrs_has_attr proc
    jmp qword ptr [g_real_exports + 776]
p_il2cpp_custom_attrs_has_attr endp

p_il2cpp_debug_get_method_info proc
    jmp qword ptr [g_real_exports + 784]
p_il2cpp_debug_get_method_info endp

p_il2cpp_debugger_set_agent_options proc
    jmp qword ptr [g_real_exports + 792]
p_il2cpp_debugger_set_agent_options endp

p_il2cpp_domain_assembly_open proc
    jmp qword ptr [g_real_exports + 800]
p_il2cpp_domain_assembly_open endp

p_il2cpp_domain_get proc
    jmp qword ptr [g_real_exports + 808]
p_il2cpp_domain_get endp

p_il2cpp_domain_get_assemblies proc
    jmp qword ptr [g_real_exports + 816]
p_il2cpp_domain_get_assemblies endp

p_il2cpp_exception_from_name_msg proc
    jmp qword ptr [g_real_exports + 824]
p_il2cpp_exception_from_name_msg endp

p_il2cpp_field_get_flags proc
    jmp qword ptr [g_real_exports + 832]
p_il2cpp_field_get_flags endp

p_il2cpp_field_get_name proc
    jmp qword ptr [g_real_exports + 840]
p_il2cpp_field_get_name endp

p_il2cpp_field_get_offset proc
    jmp qword ptr [g_real_exports + 848]
p_il2cpp_field_get_offset endp

p_il2cpp_field_get_parent proc
    jmp qword ptr [g_real_exports + 856]
p_il2cpp_field_get_parent endp

p_il2cpp_field_get_type proc
    jmp qword ptr [g_real_exports + 864]
p_il2cpp_field_get_type endp

p_il2cpp_field_get_value proc
    jmp qword ptr [g_real_exports + 872]
p_il2cpp_field_get_value endp

p_il2cpp_field_get_value_object proc
    jmp qword ptr [g_real_exports + 880]
p_il2cpp_field_get_value_object endp

p_il2cpp_field_has_attribute proc
    jmp qword ptr [g_real_exports + 888]
p_il2cpp_field_has_attribute endp

p_il2cpp_field_is_literal proc
    jmp qword ptr [g_real_exports + 896]
p_il2cpp_field_is_literal endp

p_il2cpp_field_set_value proc
    jmp qword ptr [g_real_exports + 904]
p_il2cpp_field_set_value endp

p_il2cpp_field_set_value_object proc
    jmp qword ptr [g_real_exports + 912]
p_il2cpp_field_set_value_object endp

p_il2cpp_field_static_get_value proc
    jmp qword ptr [g_real_exports + 920]
p_il2cpp_field_static_get_value endp

p_il2cpp_field_static_set_value proc
    jmp qword ptr [g_real_exports + 928]
p_il2cpp_field_static_set_value endp

p_il2cpp_format_exception proc
    jmp qword ptr [g_real_exports + 936]
p_il2cpp_format_exception endp

p_il2cpp_format_stack_trace proc
    jmp qword ptr [g_real_exports + 944]
p_il2cpp_format_stack_trace endp

p_il2cpp_free proc
    jmp qword ptr [g_real_exports + 952]
p_il2cpp_free endp

p_il2cpp_free_captured_memory_snapshot proc
    jmp qword ptr [g_real_exports + 960]
p_il2cpp_free_captured_memory_snapshot endp

p_il2cpp_gc_alloc_fixed proc
    jmp qword ptr [g_real_exports + 968]
p_il2cpp_gc_alloc_fixed endp

p_il2cpp_gc_collect proc
    jmp qword ptr [g_real_exports + 976]
p_il2cpp_gc_collect endp

p_il2cpp_gc_collect_a_little proc
    jmp qword ptr [g_real_exports + 984]
p_il2cpp_gc_collect_a_little endp

p_il2cpp_gc_disable proc
    jmp qword ptr [g_real_exports + 992]
p_il2cpp_gc_disable endp

p_il2cpp_gc_enable proc
    jmp qword ptr [g_real_exports + 1000]
p_il2cpp_gc_enable endp

p_il2cpp_gc_foreach_heap proc
    jmp qword ptr [g_real_exports + 1008]
p_il2cpp_gc_foreach_heap endp

p_il2cpp_gc_free_fixed proc
    jmp qword ptr [g_real_exports + 1016]
p_il2cpp_gc_free_fixed endp

p_il2cpp_gc_get_heap_size proc
    jmp qword ptr [g_real_exports + 1024]
p_il2cpp_gc_get_heap_size endp

p_il2cpp_gc_get_max_time_slice_ns proc
    jmp qword ptr [g_real_exports + 1032]
p_il2cpp_gc_get_max_time_slice_ns endp

p_il2cpp_gc_get_used_size proc
    jmp qword ptr [g_real_exports + 1040]
p_il2cpp_gc_get_used_size endp

p_il2cpp_gc_has_strict_wbarriers proc
    jmp qword ptr [g_real_exports + 1048]
p_il2cpp_gc_has_strict_wbarriers endp

p_il2cpp_gc_is_disabled proc
    jmp qword ptr [g_real_exports + 1056]
p_il2cpp_gc_is_disabled endp

p_il2cpp_gc_is_incremental proc
    jmp qword ptr [g_real_exports + 1064]
p_il2cpp_gc_is_incremental endp

p_il2cpp_gc_set_external_allocation_tracker proc
    jmp qword ptr [g_real_exports + 1072]
p_il2cpp_gc_set_external_allocation_tracker endp

p_il2cpp_gc_set_external_wbarrier_tracker proc
    jmp qword ptr [g_real_exports + 1080]
p_il2cpp_gc_set_external_wbarrier_tracker endp

p_il2cpp_gc_set_max_time_slice_ns proc
    jmp qword ptr [g_real_exports + 1088]
p_il2cpp_gc_set_max_time_slice_ns endp

p_il2cpp_gc_set_mode proc
    jmp qword ptr [g_real_exports + 1096]
p_il2cpp_gc_set_mode endp

p_il2cpp_gc_start_incremental_collection proc
    jmp qword ptr [g_real_exports + 1104]
p_il2cpp_gc_start_incremental_collection endp

p_il2cpp_gc_wbarrier_set_field proc
    jmp qword ptr [g_real_exports + 1112]
p_il2cpp_gc_wbarrier_set_field endp

p_il2cpp_gchandle_foreach_get_target proc
    jmp qword ptr [g_real_exports + 1120]
p_il2cpp_gchandle_foreach_get_target endp

p_il2cpp_gchandle_free proc
    jmp qword ptr [g_real_exports + 1128]
p_il2cpp_gchandle_free endp

p_il2cpp_gchandle_get_target proc
    jmp qword ptr [g_real_exports + 1136]
p_il2cpp_gchandle_get_target endp

p_il2cpp_gchandle_new proc
    jmp qword ptr [g_real_exports + 1144]
p_il2cpp_gchandle_new endp

p_il2cpp_gchandle_new_weakref proc
    jmp qword ptr [g_real_exports + 1152]
p_il2cpp_gchandle_new_weakref endp

p_il2cpp_get_corlib proc
    jmp qword ptr [g_real_exports + 1160]
p_il2cpp_get_corlib endp

p_il2cpp_get_exception_argument_null proc
    jmp qword ptr [g_real_exports + 1168]
p_il2cpp_get_exception_argument_null endp

p_il2cpp_image_get_assembly proc
    jmp qword ptr [g_real_exports + 1176]
p_il2cpp_image_get_assembly endp

p_il2cpp_image_get_class proc
    jmp qword ptr [g_real_exports + 1184]
p_il2cpp_image_get_class endp

p_il2cpp_image_get_class_count proc
    jmp qword ptr [g_real_exports + 1192]
p_il2cpp_image_get_class_count endp

p_il2cpp_image_get_entry_point proc
    jmp qword ptr [g_real_exports + 1200]
p_il2cpp_image_get_entry_point endp

p_il2cpp_image_get_filename proc
    jmp qword ptr [g_real_exports + 1208]
p_il2cpp_image_get_filename endp

p_il2cpp_image_get_name proc
    jmp qword ptr [g_real_exports + 1216]
p_il2cpp_image_get_name endp

p_il2cpp_is_debugger_attached proc
    jmp qword ptr [g_real_exports + 1240]
p_il2cpp_is_debugger_attached endp

p_il2cpp_is_vm_thread proc
    jmp qword ptr [g_real_exports + 1248]
p_il2cpp_is_vm_thread endp

p_il2cpp_memory_pool_get_region_size proc
    jmp qword ptr [g_real_exports + 1256]
p_il2cpp_memory_pool_get_region_size endp

p_il2cpp_memory_pool_set_region_size proc
    jmp qword ptr [g_real_exports + 1264]
p_il2cpp_memory_pool_set_region_size endp

p_il2cpp_method_get_class proc
    jmp qword ptr [g_real_exports + 1272]
p_il2cpp_method_get_class endp

p_il2cpp_method_get_declaring_type proc
    jmp qword ptr [g_real_exports + 1280]
p_il2cpp_method_get_declaring_type endp

p_il2cpp_method_get_flags proc
    jmp qword ptr [g_real_exports + 1288]
p_il2cpp_method_get_flags endp

p_il2cpp_method_get_from_reflection proc
    jmp qword ptr [g_real_exports + 1296]
p_il2cpp_method_get_from_reflection endp

p_il2cpp_method_get_name proc
    jmp qword ptr [g_real_exports + 1304]
p_il2cpp_method_get_name endp

p_il2cpp_method_get_object proc
    jmp qword ptr [g_real_exports + 1312]
p_il2cpp_method_get_object endp

p_il2cpp_method_get_param proc
    jmp qword ptr [g_real_exports + 1320]
p_il2cpp_method_get_param endp

p_il2cpp_method_get_param_count proc
    jmp qword ptr [g_real_exports + 1328]
p_il2cpp_method_get_param_count endp

p_il2cpp_method_get_param_name proc
    jmp qword ptr [g_real_exports + 1336]
p_il2cpp_method_get_param_name endp

p_il2cpp_method_get_return_type proc
    jmp qword ptr [g_real_exports + 1344]
p_il2cpp_method_get_return_type endp

p_il2cpp_method_get_token proc
    jmp qword ptr [g_real_exports + 1352]
p_il2cpp_method_get_token endp

p_il2cpp_method_has_attribute proc
    jmp qword ptr [g_real_exports + 1360]
p_il2cpp_method_has_attribute endp

p_il2cpp_method_is_generic proc
    jmp qword ptr [g_real_exports + 1368]
p_il2cpp_method_is_generic endp

p_il2cpp_method_is_inflated proc
    jmp qword ptr [g_real_exports + 1376]
p_il2cpp_method_is_inflated endp

p_il2cpp_method_is_instance proc
    jmp qword ptr [g_real_exports + 1384]
p_il2cpp_method_is_instance endp

p_il2cpp_monitor_enter proc
    jmp qword ptr [g_real_exports + 1392]
p_il2cpp_monitor_enter endp

p_il2cpp_monitor_exit proc
    jmp qword ptr [g_real_exports + 1400]
p_il2cpp_monitor_exit endp

p_il2cpp_monitor_pulse proc
    jmp qword ptr [g_real_exports + 1408]
p_il2cpp_monitor_pulse endp

p_il2cpp_monitor_pulse_all proc
    jmp qword ptr [g_real_exports + 1416]
p_il2cpp_monitor_pulse_all endp

p_il2cpp_monitor_try_enter proc
    jmp qword ptr [g_real_exports + 1424]
p_il2cpp_monitor_try_enter endp

p_il2cpp_monitor_try_wait proc
    jmp qword ptr [g_real_exports + 1432]
p_il2cpp_monitor_try_wait endp

p_il2cpp_monitor_wait proc
    jmp qword ptr [g_real_exports + 1440]
p_il2cpp_monitor_wait endp

p_il2cpp_native_stack_trace proc
    jmp qword ptr [g_real_exports + 1448]
p_il2cpp_native_stack_trace endp

p_il2cpp_object_get_class proc
    jmp qword ptr [g_real_exports + 1456]
p_il2cpp_object_get_class endp

p_il2cpp_object_get_size proc
    jmp qword ptr [g_real_exports + 1464]
p_il2cpp_object_get_size endp

p_il2cpp_object_get_virtual_method proc
    jmp qword ptr [g_real_exports + 1472]
p_il2cpp_object_get_virtual_method endp

p_il2cpp_object_header_size proc
    jmp qword ptr [g_real_exports + 1480]
p_il2cpp_object_header_size endp

p_il2cpp_object_new proc
    jmp qword ptr [g_real_exports + 1488]
p_il2cpp_object_new endp

p_il2cpp_object_unbox proc
    jmp qword ptr [g_real_exports + 1496]
p_il2cpp_object_unbox endp

p_il2cpp_offset_of_array_bounds_in_array_object_header proc
    jmp qword ptr [g_real_exports + 1504]
p_il2cpp_offset_of_array_bounds_in_array_object_header endp

p_il2cpp_offset_of_array_length_in_array_object_header proc
    jmp qword ptr [g_real_exports + 1512]
p_il2cpp_offset_of_array_length_in_array_object_header endp

p_il2cpp_override_stack_backtrace proc
    jmp qword ptr [g_real_exports + 1520]
p_il2cpp_override_stack_backtrace endp

p_il2cpp_profiler_install proc
    jmp qword ptr [g_real_exports + 1528]
p_il2cpp_profiler_install endp

p_il2cpp_profiler_install_allocation proc
    jmp qword ptr [g_real_exports + 1536]
p_il2cpp_profiler_install_allocation endp

p_il2cpp_profiler_install_enter_leave proc
    jmp qword ptr [g_real_exports + 1544]
p_il2cpp_profiler_install_enter_leave endp

p_il2cpp_profiler_install_fileio proc
    jmp qword ptr [g_real_exports + 1552]
p_il2cpp_profiler_install_fileio endp

p_il2cpp_profiler_install_gc proc
    jmp qword ptr [g_real_exports + 1560]
p_il2cpp_profiler_install_gc endp

p_il2cpp_profiler_install_thread proc
    jmp qword ptr [g_real_exports + 1568]
p_il2cpp_profiler_install_thread endp

p_il2cpp_profiler_set_events proc
    jmp qword ptr [g_real_exports + 1576]
p_il2cpp_profiler_set_events endp

p_il2cpp_property_get_flags proc
    jmp qword ptr [g_real_exports + 1584]
p_il2cpp_property_get_flags endp

p_il2cpp_property_get_get_method proc
    jmp qword ptr [g_real_exports + 1592]
p_il2cpp_property_get_get_method endp

p_il2cpp_property_get_name proc
    jmp qword ptr [g_real_exports + 1600]
p_il2cpp_property_get_name endp

p_il2cpp_property_get_parent proc
    jmp qword ptr [g_real_exports + 1608]
p_il2cpp_property_get_parent endp

p_il2cpp_property_get_set_method proc
    jmp qword ptr [g_real_exports + 1616]
p_il2cpp_property_get_set_method endp

p_il2cpp_raise_exception proc
    jmp qword ptr [g_real_exports + 1624]
p_il2cpp_raise_exception endp

p_il2cpp_register_debugger_agent_transport proc
    jmp qword ptr [g_real_exports + 1632]
p_il2cpp_register_debugger_agent_transport endp

p_il2cpp_register_log_callback proc
    jmp qword ptr [g_real_exports + 1640]
p_il2cpp_register_log_callback endp

p_il2cpp_resolve_icall proc
    jmp qword ptr [g_real_exports + 1648]
p_il2cpp_resolve_icall endp

p_il2cpp_runtime_class_init proc
    jmp qword ptr [g_real_exports + 1656]
p_il2cpp_runtime_class_init endp

p_il2cpp_runtime_invoke proc
    jmp qword ptr [g_real_exports + 1664]
p_il2cpp_runtime_invoke endp

p_il2cpp_runtime_invoke_convert_args proc
    jmp qword ptr [g_real_exports + 1672]
p_il2cpp_runtime_invoke_convert_args endp

p_il2cpp_runtime_object_init proc
    jmp qword ptr [g_real_exports + 1680]
p_il2cpp_runtime_object_init endp

p_il2cpp_runtime_object_init_exception proc
    jmp qword ptr [g_real_exports + 1688]
p_il2cpp_runtime_object_init_exception endp

p_il2cpp_runtime_unhandled_exception_policy_set proc
    jmp qword ptr [g_real_exports + 1696]
p_il2cpp_runtime_unhandled_exception_policy_set endp

p_il2cpp_set_commandline_arguments proc
    jmp qword ptr [g_real_exports + 1704]
p_il2cpp_set_commandline_arguments endp

p_il2cpp_set_commandline_arguments_utf16 proc
    jmp qword ptr [g_real_exports + 1712]
p_il2cpp_set_commandline_arguments_utf16 endp

p_il2cpp_set_config proc
    jmp qword ptr [g_real_exports + 1720]
p_il2cpp_set_config endp

p_il2cpp_set_config_dir proc
    jmp qword ptr [g_real_exports + 1728]
p_il2cpp_set_config_dir endp

p_il2cpp_set_config_utf16 proc
    jmp qword ptr [g_real_exports + 1736]
p_il2cpp_set_config_utf16 endp

p_il2cpp_set_data_dir proc
    jmp qword ptr [g_real_exports + 1744]
p_il2cpp_set_data_dir endp

p_il2cpp_set_default_thread_affinity proc
    jmp qword ptr [g_real_exports + 1752]
p_il2cpp_set_default_thread_affinity endp

p_il2cpp_set_find_plugin_callback proc
    jmp qword ptr [g_real_exports + 1760]
p_il2cpp_set_find_plugin_callback endp

p_il2cpp_set_memory_callbacks proc
    jmp qword ptr [g_real_exports + 1768]
p_il2cpp_set_memory_callbacks endp

p_il2cpp_set_temp_dir proc
    jmp qword ptr [g_real_exports + 1776]
p_il2cpp_set_temp_dir endp

p_il2cpp_shutdown proc
    jmp qword ptr [g_real_exports + 1784]
p_il2cpp_shutdown endp

p_il2cpp_start_gc_world proc
    jmp qword ptr [g_real_exports + 1792]
p_il2cpp_start_gc_world endp

p_il2cpp_stats_dump_to_file proc
    jmp qword ptr [g_real_exports + 1800]
p_il2cpp_stats_dump_to_file endp

p_il2cpp_stats_get_value proc
    jmp qword ptr [g_real_exports + 1808]
p_il2cpp_stats_get_value endp

p_il2cpp_stop_gc_world proc
    jmp qword ptr [g_real_exports + 1816]
p_il2cpp_stop_gc_world endp

p_il2cpp_string_chars proc
    jmp qword ptr [g_real_exports + 1824]
p_il2cpp_string_chars endp

p_il2cpp_string_intern proc
    jmp qword ptr [g_real_exports + 1832]
p_il2cpp_string_intern endp

p_il2cpp_string_is_interned proc
    jmp qword ptr [g_real_exports + 1840]
p_il2cpp_string_is_interned endp

p_il2cpp_string_length proc
    jmp qword ptr [g_real_exports + 1848]
p_il2cpp_string_length endp

p_il2cpp_string_new proc
    jmp qword ptr [g_real_exports + 1856]
p_il2cpp_string_new endp

p_il2cpp_string_new_len proc
    jmp qword ptr [g_real_exports + 1864]
p_il2cpp_string_new_len endp

p_il2cpp_string_new_utf16 proc
    jmp qword ptr [g_real_exports + 1872]
p_il2cpp_string_new_utf16 endp

p_il2cpp_string_new_wrapper proc
    jmp qword ptr [g_real_exports + 1880]
p_il2cpp_string_new_wrapper endp

p_il2cpp_thread_attach proc
    jmp qword ptr [g_real_exports + 1888]
p_il2cpp_thread_attach endp

p_il2cpp_thread_current proc
    jmp qword ptr [g_real_exports + 1896]
p_il2cpp_thread_current endp

p_il2cpp_thread_detach proc
    jmp qword ptr [g_real_exports + 1904]
p_il2cpp_thread_detach endp

p_il2cpp_thread_get_all_attached_threads proc
    jmp qword ptr [g_real_exports + 1912]
p_il2cpp_thread_get_all_attached_threads endp

p_il2cpp_thread_get_frame_at proc
    jmp qword ptr [g_real_exports + 1920]
p_il2cpp_thread_get_frame_at endp

p_il2cpp_thread_get_stack_depth proc
    jmp qword ptr [g_real_exports + 1928]
p_il2cpp_thread_get_stack_depth endp

p_il2cpp_thread_get_top_frame proc
    jmp qword ptr [g_real_exports + 1936]
p_il2cpp_thread_get_top_frame endp

p_il2cpp_thread_walk_frame_stack proc
    jmp qword ptr [g_real_exports + 1944]
p_il2cpp_thread_walk_frame_stack endp

p_il2cpp_type_equals proc
    jmp qword ptr [g_real_exports + 1952]
p_il2cpp_type_equals endp

p_il2cpp_type_get_assembly_qualified_name proc
    jmp qword ptr [g_real_exports + 1960]
p_il2cpp_type_get_assembly_qualified_name endp

p_il2cpp_type_get_attrs proc
    jmp qword ptr [g_real_exports + 1968]
p_il2cpp_type_get_attrs endp

p_il2cpp_type_get_class_or_element_class proc
    jmp qword ptr [g_real_exports + 1976]
p_il2cpp_type_get_class_or_element_class endp

p_il2cpp_type_get_name proc
    jmp qword ptr [g_real_exports + 1984]
p_il2cpp_type_get_name endp

p_il2cpp_type_get_name_chunked proc
    jmp qword ptr [g_real_exports + 1992]
p_il2cpp_type_get_name_chunked endp

p_il2cpp_type_get_object proc
    jmp qword ptr [g_real_exports + 2000]
p_il2cpp_type_get_object endp

p_il2cpp_type_get_reflection_name proc
    jmp qword ptr [g_real_exports + 2008]
p_il2cpp_type_get_reflection_name endp

p_il2cpp_type_get_type proc
    jmp qword ptr [g_real_exports + 2016]
p_il2cpp_type_get_type endp

p_il2cpp_type_is_byref proc
    jmp qword ptr [g_real_exports + 2024]
p_il2cpp_type_is_byref endp

p_il2cpp_type_is_pointer_type proc
    jmp qword ptr [g_real_exports + 2032]
p_il2cpp_type_is_pointer_type endp

p_il2cpp_type_is_static proc
    jmp qword ptr [g_real_exports + 2040]
p_il2cpp_type_is_static endp

p_il2cpp_unhandled_exception proc
    jmp qword ptr [g_real_exports + 2048]
p_il2cpp_unhandled_exception endp

p_il2cpp_unity_install_unitytls_interface proc
    jmp qword ptr [g_real_exports + 2056]
p_il2cpp_unity_install_unitytls_interface endp

p_il2cpp_unity_liveness_allocate_struct proc
    jmp qword ptr [g_real_exports + 2064]
p_il2cpp_unity_liveness_allocate_struct endp

p_il2cpp_unity_liveness_calculation_from_root proc
    jmp qword ptr [g_real_exports + 2072]
p_il2cpp_unity_liveness_calculation_from_root endp

p_il2cpp_unity_liveness_calculation_from_statics proc
    jmp qword ptr [g_real_exports + 2080]
p_il2cpp_unity_liveness_calculation_from_statics endp

p_il2cpp_unity_liveness_finalize proc
    jmp qword ptr [g_real_exports + 2088]
p_il2cpp_unity_liveness_finalize endp

p_il2cpp_unity_liveness_free_struct proc
    jmp qword ptr [g_real_exports + 2096]
p_il2cpp_unity_liveness_free_struct endp

p_il2cpp_unity_set_android_network_up_state_func proc
    jmp qword ptr [g_real_exports + 2104]
p_il2cpp_unity_set_android_network_up_state_func endp

p_il2cpp_value_box proc
    jmp qword ptr [g_real_exports + 2112]
p_il2cpp_value_box endp

p_jinfo_get_method proc
    jmp qword ptr [g_real_exports + 2120]
p_jinfo_get_method endp

p_mini_get_interp_callbacks proc
    jmp qword ptr [g_real_exports + 2128]
p_mini_get_interp_callbacks endp

p_mini_jit_info_table_find proc
    jmp qword ptr [g_real_exports + 2136]
p_mini_jit_info_table_find endp

p_mono_arch_clear_breakpoint proc
    jmp qword ptr [g_real_exports + 2144]
p_mono_arch_clear_breakpoint endp

p_mono_arch_context_get_int_reg proc
    jmp qword ptr [g_real_exports + 2152]
p_mono_arch_context_get_int_reg endp

p_mono_arch_context_set_int_reg proc
    jmp qword ptr [g_real_exports + 2160]
p_mono_arch_context_set_int_reg endp

p_mono_arch_set_breakpoint proc
    jmp qword ptr [g_real_exports + 2168]
p_mono_arch_set_breakpoint endp

p_mono_arch_setup_resume_sighandler_ctx proc
    jmp qword ptr [g_real_exports + 2176]
p_mono_arch_setup_resume_sighandler_ctx endp

p_mono_arch_skip_breakpoint proc
    jmp qword ptr [g_real_exports + 2184]
p_mono_arch_skip_breakpoint endp

p_mono_arch_skip_single_step proc
    jmp qword ptr [g_real_exports + 2192]
p_mono_arch_skip_single_step endp

p_mono_arch_start_single_stepping proc
    jmp qword ptr [g_real_exports + 2200]
p_mono_arch_start_single_stepping endp

p_mono_arch_stop_single_stepping proc
    jmp qword ptr [g_real_exports + 2208]
p_mono_arch_stop_single_stepping endp

p_mono_array_element_size proc
    jmp qword ptr [g_real_exports + 2216]
p_mono_array_element_size endp

p_mono_array_length proc
    jmp qword ptr [g_real_exports + 2224]
p_mono_array_length endp

p_mono_class_get_byref_type proc
    jmp qword ptr [g_real_exports + 2232]
p_mono_class_get_byref_type endp

p_mono_class_get_checked proc
    jmp qword ptr [g_real_exports + 2240]
p_mono_class_get_checked endp

p_mono_class_get_context proc
    jmp qword ptr [g_real_exports + 2248]
p_mono_class_get_context endp

p_mono_class_get_element_class proc
    jmp qword ptr [g_real_exports + 2256]
p_mono_class_get_element_class endp

p_mono_class_get_flags proc
    jmp qword ptr [g_real_exports + 2264]
p_mono_class_get_flags endp

p_mono_class_get_image proc
    jmp qword ptr [g_real_exports + 2272]
p_mono_class_get_image endp

p_mono_class_get_interfaces proc
    jmp qword ptr [g_real_exports + 2280]
p_mono_class_get_interfaces endp

p_mono_class_get_methods proc
    jmp qword ptr [g_real_exports + 2288]
p_mono_class_get_methods endp

p_mono_class_get_name proc
    jmp qword ptr [g_real_exports + 2296]
p_mono_class_get_name endp

p_mono_class_get_namespace proc
    jmp qword ptr [g_real_exports + 2304]
p_mono_class_get_namespace endp

p_mono_class_get_nested_types proc
    jmp qword ptr [g_real_exports + 2312]
p_mono_class_get_nested_types endp

p_mono_class_get_parent proc
    jmp qword ptr [g_real_exports + 2320]
p_mono_class_get_parent endp

p_mono_class_get_properties proc
    jmp qword ptr [g_real_exports + 2328]
p_mono_class_get_properties endp

p_mono_class_get_rank proc
    jmp qword ptr [g_real_exports + 2336]
p_mono_class_get_rank endp

p_mono_class_get_type proc
    jmp qword ptr [g_real_exports + 2344]
p_mono_class_get_type endp

p_mono_class_get_type_token proc
    jmp qword ptr [g_real_exports + 2352]
p_mono_class_get_type_token endp

p_mono_class_has_parent proc
    jmp qword ptr [g_real_exports + 2360]
p_mono_class_has_parent endp

p_mono_class_instance_size proc
    jmp qword ptr [g_real_exports + 2368]
p_mono_class_instance_size endp

p_mono_class_is_enum proc
    jmp qword ptr [g_real_exports + 2376]
p_mono_class_is_enum endp

p_mono_class_is_valuetype proc
    jmp qword ptr [g_real_exports + 2384]
p_mono_class_is_valuetype endp

p_mono_class_num_fields proc
    jmp qword ptr [g_real_exports + 2392]
p_mono_class_num_fields endp

p_mono_class_num_methods proc
    jmp qword ptr [g_real_exports + 2400]
p_mono_class_num_methods endp

p_mono_class_num_properties proc
    jmp qword ptr [g_real_exports + 2408]
p_mono_class_num_properties endp

p_mono_class_value_size proc
    jmp qword ptr [g_real_exports + 2416]
p_mono_class_value_size endp

p_mono_debug_find_method proc
    jmp qword ptr [g_real_exports + 2424]
p_mono_debug_find_method endp

p_mono_debug_free_locals proc
    jmp qword ptr [g_real_exports + 2432]
p_mono_debug_free_locals endp

p_mono_debug_il_offset_from_address proc
    jmp qword ptr [g_real_exports + 2440]
p_mono_debug_il_offset_from_address endp

p_mono_debug_lookup_locals proc
    jmp qword ptr [g_real_exports + 2448]
p_mono_debug_lookup_locals endp

p_mono_domain_foreach proc
    jmp qword ptr [g_real_exports + 2456]
p_mono_domain_foreach endp

p_mono_domain_get proc
    jmp qword ptr [g_real_exports + 2464]
p_mono_domain_get endp

p_mono_domain_get_assemblies_iter proc
    jmp qword ptr [g_real_exports + 2472]
p_mono_domain_get_assemblies_iter endp

p_mono_domain_get_corlib proc
    jmp qword ptr [g_real_exports + 2480]
p_mono_domain_get_corlib endp

p_mono_domain_is_unloading proc
    jmp qword ptr [g_real_exports + 2488]
p_mono_domain_is_unloading endp

p_mono_environment_exitcode_get proc
    jmp qword ptr [g_real_exports + 2496]
p_mono_environment_exitcode_get endp

p_mono_environment_exitcode_set proc
    jmp qword ptr [g_real_exports + 2504]
p_mono_environment_exitcode_set endp

p_mono_field_get_name proc
    jmp qword ptr [g_real_exports + 2512]
p_mono_field_get_name endp

p_mono_field_get_offset proc
    jmp qword ptr [g_real_exports + 2520]
p_mono_field_get_offset endp

p_mono_field_get_parent proc
    jmp qword ptr [g_real_exports + 2528]
p_mono_field_get_parent endp

p_mono_field_get_type proc
    jmp qword ptr [g_real_exports + 2536]
p_mono_field_get_type endp

p_mono_field_set_value proc
    jmp qword ptr [g_real_exports + 2544]
p_mono_field_set_value endp

p_mono_find_prev_seq_point_for_native_offset proc
    jmp qword ptr [g_real_exports + 2552]
p_mono_find_prev_seq_point_for_native_offset endp

p_mono_free_method_signatures proc
    jmp qword ptr [g_real_exports + 2560]
p_mono_free_method_signatures endp

p_mono_gc_register_root proc
    jmp qword ptr [g_real_exports + 2568]
p_mono_gc_register_root endp

p_mono_get_byte_class proc
    jmp qword ptr [g_real_exports + 2576]
p_mono_get_byte_class endp

p_mono_get_lmf_addr proc
    jmp qword ptr [g_real_exports + 2584]
p_mono_get_lmf_addr endp

p_mono_get_root_domain proc
    jmp qword ptr [g_real_exports + 2592]
p_mono_get_root_domain endp

p_mono_get_runtime_build_info proc
    jmp qword ptr [g_real_exports + 2600]
p_mono_get_runtime_build_info endp

p_mono_get_string_class proc
    jmp qword ptr [g_real_exports + 2608]
p_mono_get_string_class endp

p_mono_image_get_assembly proc
    jmp qword ptr [g_real_exports + 2616]
p_mono_image_get_assembly endp

p_mono_image_get_entry_point proc
    jmp qword ptr [g_real_exports + 2624]
p_mono_image_get_entry_point endp

p_mono_image_get_filename proc
    jmp qword ptr [g_real_exports + 2632]
p_mono_image_get_filename endp

p_mono_image_get_guid proc
    jmp qword ptr [g_real_exports + 2640]
p_mono_image_get_guid endp

p_mono_image_get_name proc
    jmp qword ptr [g_real_exports + 2648]
p_mono_image_get_name endp

p_mono_image_is_dynamic proc
    jmp qword ptr [g_real_exports + 2656]
p_mono_image_is_dynamic endp

p_mono_jit_find_compiled_method_with_jit_info proc
    jmp qword ptr [g_real_exports + 2664]
p_mono_jit_find_compiled_method_with_jit_info endp

p_mono_jit_info_get_method proc
    jmp qword ptr [g_real_exports + 2672]
p_mono_jit_info_get_method endp

p_mono_jit_info_table_find proc
    jmp qword ptr [g_real_exports + 2680]
p_mono_jit_info_table_find endp

p_mono_marshal_method_from_wrapper proc
    jmp qword ptr [g_real_exports + 2688]
p_mono_marshal_method_from_wrapper endp

p_mono_metadata_free_mh proc
    jmp qword ptr [g_real_exports + 2696]
p_mono_metadata_free_mh endp

p_mono_metadata_generic_class_is_valuetype proc
    jmp qword ptr [g_real_exports + 2704]
p_mono_metadata_generic_class_is_valuetype endp

p_mono_method_full_name proc
    jmp qword ptr [g_real_exports + 2712]
p_mono_method_full_name endp

p_mono_method_get_class proc
    jmp qword ptr [g_real_exports + 2720]
p_mono_method_get_class endp

p_mono_method_get_context proc
    jmp qword ptr [g_real_exports + 2728]
p_mono_method_get_context endp

p_mono_method_get_declaring_generic_method proc
    jmp qword ptr [g_real_exports + 2736]
p_mono_method_get_declaring_generic_method endp

p_mono_method_get_flags proc
    jmp qword ptr [g_real_exports + 2744]
p_mono_method_get_flags endp

p_mono_method_get_generic_container proc
    jmp qword ptr [g_real_exports + 2752]
p_mono_method_get_generic_container endp

p_mono_method_get_header_checked proc
    jmp qword ptr [g_real_exports + 2760]
p_mono_method_get_header_checked endp

p_mono_method_get_name proc
    jmp qword ptr [g_real_exports + 2768]
p_mono_method_get_name endp

p_mono_method_get_param_names proc
    jmp qword ptr [g_real_exports + 2776]
p_mono_method_get_param_names endp

p_mono_method_get_token proc
    jmp qword ptr [g_real_exports + 2784]
p_mono_method_get_token endp

p_mono_method_is_generic proc
    jmp qword ptr [g_real_exports + 2792]
p_mono_method_is_generic endp

p_mono_method_is_inflated proc
    jmp qword ptr [g_real_exports + 2800]
p_mono_method_is_inflated endp

p_mono_object_get_type proc
    jmp qword ptr [g_real_exports + 2808]
p_mono_object_get_type endp

p_mono_object_unbox_internal proc
    jmp qword ptr [g_real_exports + 2816]
p_mono_object_unbox_internal endp

p_mono_pal_init proc
    jmp qword ptr [g_real_exports + 2824]
p_mono_pal_init endp

p_mono_property_get_get_method proc
    jmp qword ptr [g_real_exports + 2832]
p_mono_property_get_get_method endp

p_mono_property_get_name proc
    jmp qword ptr [g_real_exports + 2840]
p_mono_property_get_name endp

p_mono_property_get_parent proc
    jmp qword ptr [g_real_exports + 2848]
p_mono_property_get_parent endp

p_mono_property_get_set_method proc
    jmp qword ptr [g_real_exports + 2856]
p_mono_property_get_set_method endp

p_mono_restore_context proc
    jmp qword ptr [g_real_exports + 2864]
p_mono_restore_context endp

p_mono_runtime_is_shutting_down proc
    jmp qword ptr [g_real_exports + 2872]
p_mono_runtime_is_shutting_down endp

p_mono_runtime_quit proc
    jmp qword ptr [g_real_exports + 2880]
p_mono_runtime_quit endp

p_mono_set_is_debugger_attached proc
    jmp qword ptr [g_real_exports + 2888]
p_mono_set_is_debugger_attached endp

p_mono_set_lmf proc
    jmp qword ptr [g_real_exports + 2896]
p_mono_set_lmf endp

p_mono_string_chars proc
    jmp qword ptr [g_real_exports + 2904]
p_mono_string_chars endp

p_mono_string_free proc
    jmp qword ptr [g_real_exports + 2912]
p_mono_string_free endp

p_mono_string_length proc
    jmp qword ptr [g_real_exports + 2920]
p_mono_string_length endp

p_mono_string_new proc
    jmp qword ptr [g_real_exports + 2928]
p_mono_string_new endp

p_mono_thread_attach proc
    jmp qword ptr [g_real_exports + 2936]
p_mono_thread_attach endp

p_mono_thread_current proc
    jmp qword ptr [g_real_exports + 2944]
p_mono_thread_current endp

p_mono_thread_detach proc
    jmp qword ptr [g_real_exports + 2952]
p_mono_thread_detach endp

p_mono_thread_get_main proc
    jmp qword ptr [g_real_exports + 2960]
p_mono_thread_get_main endp

p_mono_thread_set_name proc
    jmp qword ptr [g_real_exports + 2968]
p_mono_thread_set_name endp

p_mono_thread_state_init_from_current proc
    jmp qword ptr [g_real_exports + 2976]
p_mono_thread_state_init_from_current endp

p_mono_thread_state_init_from_monoctx proc
    jmp qword ptr [g_real_exports + 2984]
p_mono_thread_state_init_from_monoctx endp

p_mono_thread_suspend_all_other_threads proc
    jmp qword ptr [g_real_exports + 2992]
p_mono_thread_suspend_all_other_threads endp

p_mono_type_full_name proc
    jmp qword ptr [g_real_exports + 3000]
p_mono_type_full_name endp

p_mono_type_generic_inst_is_valuetype proc
    jmp qword ptr [g_real_exports + 3008]
p_mono_type_generic_inst_is_valuetype endp

p_mono_type_get_attrs proc
    jmp qword ptr [g_real_exports + 3016]
p_mono_type_get_attrs endp

p_mono_type_get_class proc
    jmp qword ptr [g_real_exports + 3024]
p_mono_type_get_class endp

p_mono_type_get_name_full proc
    jmp qword ptr [g_real_exports + 3032]
p_mono_type_get_name_full endp

p_mono_type_get_type proc
    jmp qword ptr [g_real_exports + 3040]
p_mono_type_get_type endp

p_mono_type_is_byref proc
    jmp qword ptr [g_real_exports + 3048]
p_mono_type_is_byref endp

p_mono_type_is_generic_parameter proc
    jmp qword ptr [g_real_exports + 3056]
p_mono_type_is_generic_parameter endp

p_mono_type_is_reference proc
    jmp qword ptr [g_real_exports + 3064]
p_mono_type_is_reference endp

p_mono_type_is_struct proc
    jmp qword ptr [g_real_exports + 3072]
p_mono_type_is_struct endp

p_mono_type_size proc
    jmp qword ptr [g_real_exports + 3080]
p_mono_type_size endp

end
